apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  finalizers:
  - finalizers.packagerepository.packaging.carvel.dev/delete
  name: tas-adapter-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: harbor.harborlab.fynesy.com/tanzu-packages/tas-adapter-package-repo:1.3.1
